db:
    host: 172.2.80.5
    user: drops
    password: drops
    port: 3306
    name: drops
nats:
    url: nats://172.2.60.2:4222
redis:
    url: 172.2.60.3:6379
mail:
    host: 172.2.60.4:25

alloworigins:
    - "http://172.2.20.1"
    - "http://localhost:8080"
cookie:
    samesite: none
    secure: false
