version: "3"

services:
    nginx:
        image: nginx
        restart: always
        links:
            - auth-backend:auth-backend
            - mail-backend:mail-backend
            - run4w-backend:run4w-backend
            - team-backend:team-backend
            - payment-backend:payment-backend
            - run4w-strava:run4w-strava
            - avatar-backend:avatar-backend
            - donation-backend:donation-backend
            - newsletter-backend:newsletter-backend
            - social11-backend:social11-backend  
        volumes:
            - ./config/nginx:/etc/nginx/conf.d/
        networks:
            domain_net:
                ipv4_address: ${nginx_ip}
            api_net:
    
    nginx-admin:
        image: nginx
        restart: always
        links:
            - auth-backend:auth-backend
            - mail-backend:mail-backend
            - run4w-backend:run4w-backend
            - team-backend:team-backend
            - payment-backend:payment-backend
        ports:
            - 1337:80
        networks:
            api_net:

    nats:
        image: nats
        restart: always
        networks:
            api_net:

    auth-backend:
        image: vivaconagua/auth-backend:stage
        restart: always
        env_file: 
            - .env
        links:
            - auth-db:db
            - nats:nats
        depends_on:
            - auth-db
        networks:
            api_net:
            db_net:

    auth-db:
        image: mongo
        restart: unless-stopped
        volumes: 
            - ${VOLUMES}/auth-db/:/data/db/
        networks:
            db_net:

    mail-backend:
        image: vivaconagua/mail-backend:stage
        restart: always
        env_file:
            - .env
        links:
            - nats:nats
            - mail-db:db
            - smtp-relay:smtp
        depends_on:
            - mail-db
        env_file:
            - .env
        networks:
            api_net:
            db_net:

    mail-db:
        image: mongo
        restart: unless-stopped
        volumes: 
            - ${VOLUMES}/mail-db/:/data/db/
        networks:
            db_net:
    
    smtp-relay:
        image: maildev/maildev
        restart: always
        networks:
            api_net:

    run4w-backend:
        image: vivaconagua/run4w-backend:stage
        restart: always
        env_file:
            - .env
        links:
            - nats:nats
            - run4w-db:db
        depends_on:
            - mail-db
        env_file:
            - .env
        networks:
            api_net:
            db_net:

    run4w-db:
        image: mongo
        restart: unless-stopped
        volumes: 
            - ${VOLUMES}/run4w-db/:/data/db/
        networks:
            db_net:

    team-backend:
        image: vivaconagua/team-backend:stage
        restart: unless-stopped
        links:
            - team-db:db
        env_file:
            - .env
        networks:
            api_net:
            db_net:

    team-db:
        image: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${TEAM_DB_NAME}
            - MYSQL_USER=${TEAM_DB_USER}
            - MYSQL_PASSWORD=${TEAM_DB_PASSWORD}
        env_file:
            - .env
        restart: unless-stopped
        volumes: 
            - ${VOLUMES}/team-backend/mysql/:/var/lib/mysql/
            - ./config/team-backend/db/:/docker-entrypoint-initdb.d/
        networks:
            db_net:

    payment-backend:
        image: vivaconagua/payment-backend:stage
        restart: unless-stopped
        env_file:
            - .env
        networks:
            api_net:
    
    run4w-strava:
        image: vivaconagua/run4w-strava:stage
        restart: always
        env_file:
            - .env
        links:
            - nats:nats
            - run4w-strava-db:db
        depends_on:
            - mail-db
        networks:
            api_net:
            db_net:

    run4w-strava-db:
        image: mongo
        restart: unless-stopped
        volumes: 
            - ${VOLUMES}/run4w-strava-db/:/data/db/
        networks:
            db_net:

    avatar-backend:
        image: vivaconagua/avatar-backend:stage
        restart: always
        env_file:
            - .env
        links:
            - nats:nats
            - avatar-db:db
        env_file:
            - .env
        networks:
            api_net:
            db_net:

    avatar-db:
        image: mongo
        restart: unless-stopped
        volumes: 
            - ${VOLUMES}/avatar-db/:/data/db/
        networks:
            db_net:
    
    donation-backend:
        image: vivaconagua/donation-backend:stage
        restart: always
        env_file:
            - .env
        links:
            - nats:nats
            - donation-db:db
        env_file:
            - .env
        networks:
            api_net:
            db_net:

    donation-db:
        image: mongo
        restart: unless-stopped
        volumes: 
            - ${VOLUMES}/donation-db/:/data/db/
        networks:
            db_net:

    newsletter-backend:
        image: vivaconagua/newsletter-backend:stage
        restart: always
        env_file:
            - .env
        links:
            - nats:nats
        env_file:
            - .env
        networks:
            api_net:
            db_net:

    social11-backend:
        build: .
        image: vivaconagua/social11-backend:stage
        restart: unless-stopped
        env_file:
            - .env
        links:
            - social11-db:db
        networks:
            api_net:
            db_net:
   
    social11-db:
        image: mongo
        restart: unless-stopped
        volumes: 
            - ${VOLUMES}/social11-db/:/data/db/
        networks:
            db_net:

  
networks:
  domain_net:
    external:
      name: domain_net
  api_net:
    external:
      name: api_net
  db_net:
    external:
      name: db_net
    
