
version: '3'

services:
    nginx-api:
        image: nginx
        container_name: nginx-api
        restart: unless-stopped
        volumes:
            - ./routes/:/etc/nginx/conf.d/
        networks:
            default:
                ipv4_address: 172.2.60.1
  ################
  # Architecture #
  ################
    nats-api:
        image: nats
        container_name: nats-api
        restart: unless-stopped
        networks:
            default:
                ipv4_address: 172.2.60.2

    redis-api:
        image: redis
        container_name: redis-api
        restart: unless-stopped
        networks:
            default:
                ipv4_address: 172.2.60.3

    # mail
    mail-backend:
        image: vivaconagua/mail-backend:latest
        build: ./repos/mail-backend
        container_name: mail-backend
        restart: unless-stopped
        volumes:
            - ./config/mail-backend/config.yml:/go/src/mail-backend/config/config.yml
        networks:
            default:
                ipv4_address: 172.2.60.4
     
    mail:
        image: bytemark/smtp
        restart: always
        networks:
            default:
                ipv4_address: 172.2.59.200

    ########
    # Auth #
    ########
    
    auth-backend:
        image: vivaconagua/auth-backend:latest
        build: ./repos/auth-backend
        container_name: auth-backend
        restart: unless-stopped
        volumes:
            - ./config/auth-backend/config.yml:/go/src/auth-backend/config/config.yml
        networks:
            default:
                ipv4_address: 172.2.60.5
    auth-backend-db:
        image: mysql
        container_name: auth-backend-db
        restart: unless-stopped
        env_file: ./config/auth-backend/database.env
        volumes:
            - ./volumes/auth-db/mysql/:/var/lib/mysql/
            - ./repos/auth-backend/config/db/:/docker-entrypoint-initdb.d/
        networks:
            default:
                ipv4_address: 172.2.80.5
    
    payment-backend:
        image: vivaconagua/payment-backend:latest
        build: ./repos/payment-backend
        container_name: payment-backend
        restart: unless-stopped
        volumes:
            - ./config/payment-backend/config.yml:/go/src/payment-backend/config/config.yml
        networks:
            default:
                ipv4_address: 172.2.60.6



networks:
    default:
        external:
            name: pool-network
