version: "3"

services:
    nginx:
        image: nginx:perl
        restart: always
        networks:
            api_net:

    nats:
        image: nats
        restart: always
        networks:
            api_net:

    auth-backend:
        image: auth-backend:latest
        build: .
        restart: always
        env_file: 
            - .env
        links:
            - auth-db:db
            - nats:nats
        depends_on:
            - auth-db
        networks:
            api_net:
            db_net:

    auth-db:
        image: mongo
        restart: unless-stopped
        volumes: 
            - ${VOLUMES}/auth-db/:/data/db/
        networks:
            db_net:

    mail-backend:
        build: .
        image: mail-backend:latest
        restart: always
        env_file:
            - .env
        links:
            - mail-db:db
            - smtp-relay:smtp
        depends_on:
            - mail-db
        env_file:
            - .env
        networks:
            api_net:
            db_net:

    mail-db:
        image: mongo
        restart: unless-stopped
        volumes: 
            - ${VOLUMES}/mail-db/:/data/db/
        networks:
            db_net:
    
    smtp-relay:
        image: maildev/maildev
        restart: always
        networks:
            api_net:
  
  
networks:
  api_net:
    external:
      name: api_net
  db_net:
    external:
      name: db_net
    
