
version: '3'

services:
    nginx-api:
        image: nginx
        container_name: nginx-api
        restart: unless-stopped
        volumes:
            - ./routes/nginx-api/:/etc/nginx/conf.d/
        ports:
            - 80:80
        networks:
            default:
                ipv4_address: 172.2.60.1
  ################
  # Architecture #
  ################
    nats:
        image: nats
        container_name: nats
        restart: unless-stopped
        networks:
            pool-network:
                ipv4_address: 172.2.60.2

    redis:
        image: redis
        container_name: redis
        restart: unless-stopped
        networks:
            pool-network:
                ipv4_address: 172.2.60.3

    # mail
    mail-backend:
        image: vivaconagua/mail-backend:latest
        build: ./repos/mail-backend
        container_name: mail-backend
        restart: unless-stopped
        volumes:
            - ./config/mail-backend/config.yml:/go/src/mail-backend/config.yml
        networks:
            pool-network:
                ipv4_address: 172.2.60.4


    ########
    # Auth #
    ########
    
    auth-backend:
        image: vivaconagua/auth-backend:latest
        build: ./repos/auth-backend
        container_name: auth-backend
        restart: unless-stopped
        volumes:
            - ./config/auth-backend/config.yml:/go/src/auth-backend/config.yml
        networks:
            pool-network:
                ipv4_address: 172.2.60.5
    auth-db:
        image: mysql
        container_name: auth-db
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=auth 
            - MYSQL_USER=auth
            - MYSQL_PASSWORD=auth 
            - MYSQL_ROOT_PASSWORD=yes 
        volumes:
            - ./volumes/auth-db/mysql/:/var/lib/mysql/
            - ./repos/auth-backend/db/:/docker-entrypoint-initdb.d/
        networks:
            pool-network:
                ipv4_address: 172.2.80.5
    #############
    # Dispenser #
    #############

    dispenser-backend:
        image: vivaconagua/dispenser-backend:latest
        build: ./repos/dispenser-backend
        container_name: dispenser-backend
        restart: unless-stopped
        networks:
            pool-network:
                ipv4_address: 172.2.60.6

    dispenser-db:
        image: mongo
        container_name: dispenser-database
        restart: always
        volumes: 
            - ./volumes/dispenser-db/mongodb/:/data/db/
        networks:
            pool-network:
                ipv4_address: 172.2.80.6

    ##
    # Payment
    ##
    
    payment-backend:
        image: vivaconagua/payment-backend:latest
        build: ./repos/payment-backend
        container_name: payment-backend
        restart: unless-stopped
        volumes:
            - ./config/payment-backend/config.yml:/go/src/payment-backend/config.yml
        networks:
            pool-network:
                ipv4_address: 172.3.60.7






networks:
    default:
        external:
            name: pool-network
