
version: '3'

services:
    nginx:
        image: nginx
        restart: unless-stopped
        volumes:
            - ./routes/:/etc/nginx/conf.d/
        networks:
            pool:
                ipv4_address: 172.2.60.1
            app:
    nats:
        image: nats
        restart: unless-stopped
        networks:
            app:
                aliases:
                    - api.nats
            db:

    redis:
        image: redis
        restart: unless-stopped
        networks:
            app:
                aliases:
                    - redis
networks:
    pool:
        external:
            name: pool-network
    app:
        ipam:
            driver: default
            config:
                - subnet: "172.3.0.0/21"
    db:
        ipam:
            driver: default
            config:
                - subnet: "172.3.8.0/21"
