
version: '3'

services:
    nginx:
        image: nginx
        restart: unless-stopped
        volumes:
            - ../routes/:/etc/nginx/conf.d/
        networks:
            domain_net:
            api_net:
    nats:
        image: nats
        restart: unless-stopped
        networks:
            api_net:
            db_net:

    redis:
        image: redis
        restart: unless-stopped
        networks:
            api_net:
                aliases:
                    - redis
networks:
    domain_net:
        external:
            name: domain_net
    api_net:
        external:
            name: api_net
    db_net:
        external:
            name: db_net
