-- MySQL Script generated by MySQL Workbench
-- Mo 21 Sep 2020 15:18:16 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema team
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema team
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `team` ;
USE `team` ;

-- -----------------------------------------------------
-- Table `team`.`crm_campaign`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team`.`crm_campaign` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `campaign_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `updated` BIGINT(20) NOT NULL,
  `created` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  UNIQUE INDEX `campaign_id_UNIQUE` (`campaign_id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `team`.`drops_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team`.`drops_user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(36) NOT NULL,
  `updated` BIGINT(20) NOT NULL,
  `created` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `team`.`teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team`.`teams` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `private` TINYINT NULL,
  `updated` BIGINT(20) NOT NULL,
  `created` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `team`.`team_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team`.`team_token` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `token` VARCHAR(255) NOT NULL,
  `t_case` VARCHAR(45) NOT NULL,
  `expired` BIGINT(20) NOT NULL,
  `created` VARCHAR(45) NOT NULL,
  `teams_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC) VISIBLE,
  INDEX `fk_team_token_teams1_idx` (`teams_id` ASC) VISIBLE,
  CONSTRAINT `fk_team_token_teams1`
    FOREIGN KEY (`teams_id`)
    REFERENCES `team`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `team`.`crm_campaign_has_teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team`.`crm_campaign_has_teams` (
  `crm_campaign_id` BIGINT(20) NOT NULL,
  `teams_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`crm_campaign_id`, `teams_id`),
  INDEX `fk_crm_campaign_has_teams_teams1_idx` (`teams_id` ASC) VISIBLE,
  INDEX `fk_crm_campaign_has_teams_crm_campaign1_idx` (`crm_campaign_id` ASC) VISIBLE,
  CONSTRAINT `fk_crm_campaign_has_teams_crm_campaign1`
    FOREIGN KEY (`crm_campaign_id`)
    REFERENCES `team`.`crm_campaign` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_crm_campaign_has_teams_teams1`
    FOREIGN KEY (`teams_id`)
    REFERENCES `team`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `team`.`teams_has_drops_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `team`.`teams_has_drops_user` (
  `teams_id` BIGINT(20) NOT NULL,
  `drops_user_id` BIGINT(20) NOT NULL,
  `access` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`teams_id`, `drops_user_id`),
  INDEX `fk_teams_has_drops_user_drops_user1_idx` (`drops_user_id` ASC) VISIBLE,
  INDEX `fk_teams_has_drops_user_teams1_idx` (`teams_id` ASC) VISIBLE,
  CONSTRAINT `fk_teams_has_drops_user_teams1`
    FOREIGN KEY (`teams_id`)
    REFERENCES `team`.`teams` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_teams_has_drops_user_drops_user1`
    FOREIGN KEY (`drops_user_id`)
    REFERENCES `team`.`drops_user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
